application:
  security:
    jwt:
      secret: AZXPIS0xHoyHEUna7JkrLcpmXQVBBOZAEgNwAOKw0hfG1lmGNMC9AdNUp51iYqlE
      token-duration: 1800000

spring:
  datasource:
    url: jdbc:h2:mem:homelab_inventory;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations: classpath*:db/data.sql,classpath*:db/data-dev.sql