INSERT INTO hi_device(ID, NAME, BRAND) VALUES (1, 'Light 1', 'Philips');
INSERT INTO hi_device(ID, NAME, BRAND) VALUES (2, 'Light 2', 'Aqara');
INSERT INTO hi_device(ID, NAME, BRAND) VALUES (3, 'Light 3', 'NanoLeaf');
INSERT INTO hi_device(ID, NAME, BRAND) VALUES (4, 'Sensor 1', 'Philips');
INSERT INTO hi_device(ID, NAME, BRAND) VALUES (5, 'Sensor 2', 'Aqara');
INSERT INTO hi_device(ID, NAME, BRAND) VALUES (6, 'Sensor 3', 'Philips');
INSERT INTO hi_device(ID, NAME, BRAND) VALUES (7, 'Switch 1', 'Philips');
INSERT INTO hi_device(ID, NAME, BRAND) VALUES (8, 'Switch 2', 'Aqara');
INSERT INTO hi_device(ID, NAME, BRAND) VALUES (9, 'Switch 3', 'Philips');