INSERT INTO hi_device(NAME, BRAND) VALUES ('Light 1', 'Philips');
INSERT INTO hi_device(NAME, BRAND) VALUES ('Light 2', 'Aqara');
INSERT INTO hi_device(NAME, BRAND) VALUES ('Light 3', 'NanoLeaf');
INSERT INTO hi_device(NAME, BRAND) VALUES ('Sensor 1', 'Philips');
INSERT INTO hi_device(NAME, BRAND) VALUES ('Sensor 2', 'Aqara');
INSERT INTO hi_device(NAME, BRAND) VALUES ('Sensor 3', 'Philips');
INSERT INTO hi_device(NAME, BRAND) VALUES ('Switch 1', 'Philips');
INSERT INTO hi_device(NAME, BRAND) VALUES ('Switch 2', 'Aqara');
INSERT INTO hi_device(NAME, BRAND) VALUES ('Switch 3', 'Philips');