CREATE TABLE IF NOT EXISTS hi_user (
     ID         UUID DEFAULT UUID() PRIMARY KEY,
     FIRST_NAME VARCHAR(256) NOT NULL,
     LAST_NAME  VARCHAR(256) NOT NULL,
     EMAIL      VARCHAR(256) NOT NULL,
     PASSWORD   VARCHAR(256) NOT NULL,
     ROLE       VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS hi_device (
    ID      UUID DEFAULT UUID() PRIMARY KEY,
    NAME    VARCHAR(256) NOT NULL,
    BRAND   VARCHAR(256) NOT NULL
);